### ISSUE TITLE
Make comments tests faster

### ISSUE THREAD

**Issue by voodoorai2000** [consuldemocracy/consuldemocracy#2637]
## Context

Many models can be commented (debates, proposals, investments, polls).

Comments for all these models work pretty much the same way, however we have a large duplication of these specs and these tests take a long time to run.

## What

Create a single `spec/system/comments_spec.rb` file and add tests for every scenario involving comments while also covering every model that accepts comments.

A similar task was done in pull request #3713.

**Comment by atzorvas** [comment]
I'll pick this up

**Comment by voodoorai2000** [comment]
Great @atzorvas! 👍

**Comment by javierm** [comment]
@atzorvas Are you still working on this issue?
