### ISSUE TITLE
Add a rake task to upgrade CONSUL from a previous version

### ISSUE THREAD

**Issue by voodoorai2000** [consuldemocracy/consuldemocracy#2831]
Context
===
Most [Releases](https://github.com/consul/consul/releases) require a custom rake task to be executed in order to upgrade to the next version

What
===
Add a rake task `consul:upgrade` that understands the [current version](https://github.com/consul/consul/blob/master/app/controllers/installation_controller.rb#L15) and executes the necessary rake tasks for the next version

How
===
Suggested implementation:
- Creating a database table to store the the last version upgraded
- Executing any previous rake tasks in `consul:upgrade`
- Updating the last version executed in the database table

**Comment by gabteles** [comment]
I can do this one @voodoorai2000

**Comment by javierm** [comment]
The process to upgrade was simplified in #3590. After a few years using it, I'd say it's good enough :thinking:.
