### ISSUE TITLE
Undo votes

### ISSUE THREAD

**Issue by Michael1337** [consuldemocracy/consuldemocracy#4021]
### Description
When I give a thumbs up or down on a debate or comment, I can only switch between up and down, but not remove my vote. I want to be able to remove my vote in case I have second thoughts and need more time to decide. If it is intended to not be able to undo a vote, I want to know why that is before I vote and I want to know why I can still change between up and down.

### Current Behavior
When I click on thumbs up on a vote they I already gave a thumbs up for, nothing happens. If I click on thumbs down, it changes my vote. And vice versa.

### Expected Behavior
When I click on thumbs up on a vote they I already gave a thumbs up for, my vote should be removed. Same for thumbs down. 

### Steps to reproduce
Click on any thumbs up or down and try to remove your vote.

**Comment by javierm** [comment]
Closed via #5118.
