### ISSUE TITLE
Use URL blobs for documents

### ISSUE THREAD

**Issue by decabeza** [consuldemocracy/consuldemocracy#5112]
### User Story

Administrators can upload documents from [Admin > Site content > Documents](https://demo.consulproject.org/admin/site_customization/documents).

Usually they want to link to it within the web site, so they open the document and copy the URL.

The problem is that `ActiveDirectory` creates different links for different computers so when a different user tries to open the file it doesn't work.

### Description

When the document is opened, the URL generated is:
`https://demo.consulproject.org/rails/active_storage/disk/.../dummy.pdf`

The solution is for the administrator to use _**right click > copy link**_ to get the absolute URL: `https://demo.consulproject.org/rails/active_storage/blobs/../dummy.pdf` but this is not very intuitive. 😅 

### Definition of Done
Maybe it's a good idea to replace the document URL link to File name and add the "view document" and "copy link" actions.

### Before
![before](https://user-images.githubusercontent.com/631897/236428728-709f944c-7c5d-4708-9c78-f2cf512091c5.png)

### After
![after](https://user-images.githubusercontent.com/631897/236430599-77d5f2b0-532c-409e-bda4-076986817fca.png)

**Comment by javierm** [comment]
@decabeza Could you confirm whether this issue still applies to version 2.0? We haven't been able to reproduce it in the demo :thinking:.

Thanks!

**Comment by decabeza** [comment]
I'm closing this issue because I just tested it and it seems to be fixed in the new version. 🎉
