### ISSUE TITLE
InvalidAuthenticityToken when voting a comment

### ISSUE THREAD

**Issue by javierm** [consuldemocracy/consuldemocracy#5160]
## Steps to reproduce

1. Without signing in, go to the main Participatory Budgeting page
2. Click on a heading
3. Click on an investment which has at least one comment
4. Click on the "I agree" button to agree with the comment

## Expected result

You're redirected to the sign in page

## Actual result

You get a 422 ActionController::InvalidAuthenticityToken error.

## Notes

* The same issue might be happening in other places, since it seems to be related to Turbolinks and the CSRF token
* Pull request #5118 deals with votes, so we need to check whether this behavior persists with the changes in that pull request

Thanks @decabeza and @microweb10 for reporting! :wink:

**Comment by microweb10** [comment]
No problem! 😉 
We have temporarily applied a patch by using the method `$.rails.refreshCSRFTokens()`
In case anyone is interested, the commit can be found [here](https://github.com/democrateam/consul/pull/137/commits/19af86728865987053fe27f5f5b840fbcf8962b3).

**Comment by javierm** [comment]
@microweb10 @decabeza I'm not able to reproduce this issue on the demo anymore :thinking:. Could you check whether you're able to reproduce it? Maybe I'm doing something wrong...

**Comment by microweb10** [comment]
I was just able to reproduce it. 😅 

![Captura de Pantalla 2023-08-08 a las 11 35 03](https://github.com/consuldemocracy/consuldemocracy/assets/942995/66d2a2c2-c586-4643-a529-936b514727ad)

**Comment by javierm** [comment]
Today I can reproduce it as well :sweat_smile:.

**Comment by Senen** [comment]
>Pull request https://github.com/consuldemocracy/consuldemocracy/pull/5118 deals with votes, so we need to check whether this behavior persists with the changes in that pull request

Hi @javierm, the error still happens with the #5118 changes. I've just opened a PR to include the Democrateam fix.
