### ISSUE TITLE
Custom Information Texts are not rendering in Layouts

### ISSUE THREAD

**Issue by coslajohn** [consuldemocracy/consuldemocracy#5164]
When changing the content of the custom information texts they are not rendering on the page.

This always worked ok previously but has stopped working in 2.0.0

Specific example

Site Content/Custom Information Texts/Layouts 

change layouts.header.debates from Debates to Conversations
![image](https://github.com/consuldemocracy/consuldemocracy/assets/102246590/c4d11190-7c31-4fa3-a416-8dcffd4791c6)

Save should cause the new text to be rendered but it doesn't change

![image](https://github.com/consuldemocracy/consuldemocracy/assets/102246590/09b1d14e-8cf4-4668-89d8-824d71e411f7)

I have tested this on my own instance of 2.0.0 and on the https://demo.consuldemocracy.org/

The new text is saving but the custom text isn't being rendered on the page

**Comment by javierm** [comment]
@coslajohn Thanks for reporting! It looks like the way we overwrite the `t()` method to manage translations isn't compatible with the the `ViewComponent` gem, which we use in some places.

We'll have a look before releasing version 2.0.1.
