### ISSUE TITLE
Error when trying to change the name of an image

### ISSUE THREAD

**Issue by microweb10** [consuldemocracy/consuldemocracy#5167]
### Description

When updating an image's name, the attachment should not be checked.

### Steps to reproduce in https://demo.consuldemocracy.org

1. Set the max size for images to 10Mb in [the admin section](https://demo.consuldemocracy.org/admin/settings#tab-images-and-documents).
2. Create any process that allows you to attach an image, for instance, [a new Proposal](https://demo.consuldemocracy.org/proposals/new), with an attached image of 10Mb size.
3. Set the max size for images to 1Mb in [the admin section](https://demo.consuldemocracy.org/admin/settings#tab-images-and-documents).
4. Try to edit the name of the image attached in [the edit a Proposal form](https://demo.consuldemocracy.org/proposals/7/edit).

You will get the following error message:
```
1 error prevented this Proposal from being saved. 
Please check the marked fields to know how to correct them:
```
But no field will be marked in red color.

![Screenshot](https://github.com/consuldemocracy/consuldemocracy/assets/942995/7efaf1ff-edcf-4c49-89ea-643a73000353)

**Comment by Senen** [comment]
Solved by:
*  #5168
