### ISSUE TITLE
Changing a tenant doesn't rename the attachment folders

### ISSUE THREAD

**Issue by javierm** [consuldemocracy/consuldemocracy#5239]
## Background

It's possible to edit a tenant using the administration interface in order to change its domain/subdomain.

However, attachment files associated to that tenant are stored in folders containing the domain/subdomain, and these folders aren't renamed when renaming a tenant.

This means that attachment files aren't accessible after changing the domain/subdomain of a tenant.

## Expected behavior

Attachments are still accessible after changing the domain/subdomain tenant through the administration interface.

## Workarounds

After changing the domain/subdomain of a tenant, manually rename the folder containing its attachments.

**Comment by Senen** [comment]
Hi @javierm, it seems easy to rename the folder when ActiveStorage uses `:disk`, but I do not know how it may be done when using external storage like S3, Azure or any other. Should we have as many renaming implementations as external storage Rails provides? I hope not 😬🤞🏼

We may not use the tenant schema for the active storage folder name. We may generate a random and unique slug for each tenant and use it for this kind of thing. We can show this slug in the admin tenants table so it's easy to find if someone has to dig into a tenant's storage directory. What do you think?

**Comment by javierm** [comment]
@Senen AFAIK this issue only takes place when using the `:disk` service (because we implement a custom `TenantDiskService` which introduces the issue :sweat_smile:), so we'd only need to fix it in this case.

Regarding how to fix it, so far I don't prefer (or dislike) any particular solution; it seems to me that every solution has advantages and disadvantages.

**Comment by javierm** [comment]
One thing to take into account: if we start using a slug, we probably need to implement it in a way that's compatible with existing folders or provide a rake task to migrate existing folders :thinking:.
