### ISSUE TITLE
Add account lockout on password failure

### ISSUE THREAD

**Issue by coslajohn** [consuldemocracy/consuldemocracy#5254]
### User Story

At a recent security checkup it was recommended to implement account lockout after too many failures. 

### Why is this Needed?

This is a standard security feature  and would be a useful enhancement.

### Current Behavior
[comment]: # Devise lockable seems to be supported. I have carried out some tests by enabling lockable in the devise.rb and adding :lockable to devise in the user model.

This feature seems to have been in place in the past as there is a migration which sets up the fields
Lockable
    add_column :users, :failed_attempts, :integer, default: 0, null: false
    add_column :users, :unlock_token, :string
    add_column :users, :locked_at, :datetime

The application correctly locks the account, unlocks after the specified time and correctly sends out an unlock email.

What it does not appear to do is correctly flash a notice to say that the account is locked - it still flashes Invalid Password
 
![image](https://github.com/consuldemocracy/consuldemocracy/assets/102246590/dcb26a7f-cfdd-4894-8ca5-51a1a82f5a49)

The unlock link correctly unlocks the account, but displays a view to re-send the instruction

![image](https://github.com/consuldemocracy/consuldemocracy/assets/102246590/3ff55c5b-3137-4989-b01e-2253a8f56470)

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

Account is locked after too many failures

It would be even better if lockable could be toggled on/off and the number of attempts could be changed as a configuration setting

**Comment by coslajohn** [comment]
Just to update this... the correct notices and warnings appear if in devise.rb paranoid=true is switched to paranoid=false

**Comment by coslajohn** [comment]
In my test setup with
https://github.com/consuldemocracy/consuldemocracy/commit/b9adc249bf691951656fbd93d5d2530ed7e8f254
and 
https://github.com/consuldemocracy/consuldemocracy/commit/688f1b5a6366c97cf51ef366f60937eec0f910b4

Everything works correctly except:

In the unlock email

if I click on the link from outlook it doesn't work and throws the Re-sent instructions error attached above

if I copy the link from the outlook email and paste it into url bar it works correctly and unlocks the account

if I click on the link from gmail the link works correctly and unlocks the account

**Comment by taitus** [comment]
Good morning @coslajohn ,

This is a feature we are considering for inclusion in the main repository of Consul. Here, I can link you to 3 commits that might be helpful:

- [Enable devise lockable module with default values](https://github.com/rockandror/consuldemocracy/commit/2678b207f95fbf3615dc4d2d54f242b7c8b51fb5): In this one, you can see how we enabled the `:lockable` module but without the :`last_attempt_warning` configuration. As the commit message explains, it's crucial to thoroughly understand the implications of disabling the `config.paranoid` before making this change.

- [Allow disable devise lockable through secrets](https://github.com/rockandror/consuldemocracy/commit/edc8899f98771022daf97ca507b9426768752b12): This commit allows the entire functionality to be enabled/disabled at the secrets level.

- [Allow define maximum_attempts and unlock_in](https://github.com/rockandror/consuldemocracy/commit/bdd1e1806fe2e98d06f98c070db523cadad610a2): In this commit, we allow the values to also be configured at the secrets level.

We hope to continue this development at some point. Right now, as you correctly identified, what remains is to review and fully understand the implications of disabling paranoid and see how it affects the other modules.

Regards.

**Comment by javierm** [comment]
@coslajohn Since the last comment, we've merged pull request #5273. It's now possible to enable `lockable` and configure it through the `secrets.yml` file. Do these changes solve (most of) the issue?

For now, we aren't allowing to configure the `paranoid` value, though, since we aren't sure about the legal implications.

**Comment by coslajohn** [comment]
#5273 closes this issue
