### ISSUE TITLE
Technical installation documentation conflicts with the installation instructions on the README.md

### ISSUE THREAD

**Issue by mesmoiron** [consuldemocracy/consuldemocracy#5315]
### User Story

[comment]: # (As a first time user, I want to install the app on my local computer so that I could learn to develop with the software. For some strange reason, at first it worked (the installation), but after following the simple installation instructions in the documentation, I get a jquery-gui-base theme error. After 3 installations and hours of debugging, I notice that the instructions are not the same. The right one is on the README.md page, but it refers to the wrong one in the documentation. )

### Why is this Needed?

[comment]: # The documentation should be updated, such that it doesn't cost a waste of time.

### Description

[comment]: # (Feature or Bug? eg. Type: Bug)
*Type*:

### Current Behavior
[comment]: # (Describe what actually happened.)

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

### Steps to reproduce
[comment]: # (Describe how we can replicate the bug step by step.)

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

**Comment by javierm** [comment]
Hi, @mesmoiron :smile:.

Thanks for reporting!

Closed via #5544 (although changes in the docs website will only be applied after we release version 2.2).
