### ISSUE TITLE
Technical documentation - customization section images and text gives errors, or is incomplet.

### ISSUE THREAD

**Issue by mesmoiron** [consuldemocracy/consuldemocracy#5316]
### User Story

[comment]: # As a new user, I want to test and customize consuldemocracy.  I followed the documentation to replace de logo_header.png. While doing this and the server is running, it works perfectly.  However, when I started the computer the next day, I get an error that the logo_header.png is linked to two files and conflicting. I renamed the image in the original location.

In the documentation, there's no mention that the images should be deleted in the original location. If this is the case, then the documentation should be updated.

In that same category is the customization of the texts.  Putting them in the custom folder, doesn't make any change, while the documentation says, that's the only thing to do. The only thing that works is, editing the original text files. So the instructions should be more fine-grained or explaining. Or should the server restarted every time a change is made?

### Why is this Needed?

[comment]: # This makes installation a better user experience.

### Description

[comment]: # (Feature or Bug? eg. Type: Bug)
*Type*:

### Current Behavior
[comment]: # (Describe what actually happened.)

### Expected Behavior
[comment]: # No, unnecessary,  

### Steps to reproduce
[comment]: # (Describe how we can replicate the bug step by step.)

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

**Comment by javierm** [comment]
@mesmoiron Thank you very much for reporting these issues! Please don't hesitate to report any other inaccuracies you might find.

We're recently changed the way we update the documentation, so apologies in advance because fixing these things will take some time :pray:.

**Comment by Senen** [comment]
Hi @mesmoiron, 

> In that same category is the customization of the texts. Putting them in the custom folder, doesn't make any change, while the documentation says, that's the only thing to do. The only thing that works is, editing the original text files. So the instructions should be more fine-grained or explaining. Or should the server restarted every time a change is made?

Using the custom folder usually works for me 🤔. The development environment does hot reloading for the files loaded at boot, so if you add a custom file while the server is started, you will need to restart it in order to load the new file translations.

**Comment by javierm** [comment]
Hi, @mesmoiron :smile:.

We've opened pull request #5685 to update the customization documentation. Hope this solves the issue!
