### ISSUE TITLE
Behaviour of Submit Ballot in PB Voting

### ISSUE THREAD

**Issue by coslajohn** [consuldemocracy/consuldemocracy#5322]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

### Why is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide a description of the current state, what you would like to happen, and what actually happened)
The behaviour of the the Voting is confusing for users. The Submit Ballot implies that a vote has not been made until Submit Balot is pressed.

### Current Behavior
[comment]: # (Describe what actually happened.)
When you Vote it takes you to a screen which suggests that you need to Submit Ballot. This is not clear to the user whether they have voted or not. It has caused a lot of confusion for users

When I log in (and I don't know if this is because of caching -  there doesn't appear to be any Vote Now button or link to voting?
![image](https://github.com/consuldemocracy/consuldemocracy/assets/102246590/608257f1-ecab-47d3-b024-639ce8cfd96e)

 I need to click into a project and the click back before the correct view appears
![image](https://github.com/consuldemocracy/consuldemocracy/assets/102246590/2c15db74-9bb8-431e-b91d-b99ecdbd3dee)

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
When you press the Vote button a message is flashed saying you vote has been submitted and the user can then either Vote by selecting another proposal or be taken to the Voting summary

It might be best if the voting summary is displayed permanently when viewing a budget which you are allowed to vote in.

This view appears as expected AFTER you vote

![image](https://github.com/consuldemocracy/consuldemocracy/assets/102246590/8bdcc02d-c815-43b3-857e-59b6d130a919)

A secondary request my users have asked if it is possible to have the Vote button in list view so that you can vote for multiple proposals without having to navigate in and out of proposals.

**Comment by javierm** [comment]
Regarding the first part, I agree 100%; the "Submit my ballot" button is really confusing. Maybe we could change its text to "Check my ballot" :thinking:.

**Comment by javierm** [comment]
> When I log in (and I don't know if this is because of caching - there doesn't appear to be any Vote Now button or link to voting?

It isn't related to caching; in the "list of investments" displayed on the budget's main page, there's never been a button to vote/support an investment. Maybe adding one could be a good idea :thinking:.

**Comment by javierm** [comment]
> A secondary request my users have asked if it is possible to have the Vote button in list view so that you can vote for multiple proposals without having to navigate in and out of proposals.

So there are actually people using the "list" view :smile:. Interesting idea. Thanks for reporting!

P.S. Sorry for replying in three different messages :pray:. I accidentally clicked on "comment" too early on the first one, and since you don't receive notifications when I edit a comment, ...
