### ISSUE TITLE
Add Scottish Gaelic translation

### ISSUE THREAD

**Issue by coslajohn** [consuldemocracy/consuldemocracy#5352]
The Scottish Gaelic translation was done a number of months agon now, but was never pulled into version 2.0

Can it be included in future versions

**Comment by javierm** [comment]
Hi, @coslajohn :smile:.

Thanks for reporting! @Senen Do you think we can add it as part of #5328?

**Comment by Senen** [comment]
Hi @coslajohn , @javierm,

Scottish Gaelic translations were added to Consul in the 2.0.0 version, [here is the commit](https://github.com/consuldemocracy/consuldemocracy/commit/33378229df5f63a6f19e7e0da423d4cff0c74988#diff-b77556d68d9f3201da46954b605ad8501e874118983769fcdeb2667ed76a0fdd). Maybe @coslajohn talks about enabling the in the application language selector 🤔.

Anyway, I just added a [commit](https://github.com/consuldemocracy/consuldemocracy/pull/5328/commits/cb9764becf5e5b747c70d2e16b97f5af1c5bf8f3) to #5328 to enable Scottish Gaelic, as we do with other languages.

**Comment by coslajohn** [comment]
@Senen @javierm thanks! I hadn't seen the update in the 2.0.0 release notes, and as we have been busy with other things just assumed it had been missed. Will close this now
