### ISSUE TITLE
Active storage not loading images

### ISSUE THREAD

**Issue by gzorpidis** [consuldemocracy/consuldemocracy#5391]
### User Story

I am a new user of Ruby, and when installing ConsulDemocracy via my fork, I came across the following problem: Some images do not load. 

### Description

I am suspecting this has to do with the images that are fetched using the `active_storage`. For example the loading screen loads the header image, but not the `header_background` image, and not the images below.... Below I show some images.

![1ddb255e97c09f46e5021be36e93d7e7](https://github.com/consuldemocracy/consuldemocracy/assets/52637401/8edd2805-243e-48cb-aa63-dbd5f5155221)

![8b9aab7bc79f0dadcea0bf001750a13a](https://github.com/consuldemocracy/consuldemocracy/assets/52637401/62e630ec-cc13-4c43-8ff5-77ff7254a059)

This is the console output from the server running...

`Started GET "/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDVG9JYTJWNVNTSWhjbkJvWW0xdE5YcG5lREo2TldOaVluQm5aV3h6YlRSek1tbzJZd1k2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpVldsdWJHbHVaVHNnWm1sc1pXNWhiV1U5SW1SbFltRjBaVjlpWVdOclozSnZkVzVrTG1wd1p5STdJR1pwYkdWdVlXMWxLajFWVkVZdE9DY25aR1ZpWVhSbFgySmhZMnRuY205MWJtUXVhbkJuQmpzR1ZEb1JZMjl1ZEdWdWRGOTBlWEJsU1NJUGFXMWhaMlV2YW5CbFp3WTdCbFE2RVhObGNuWnBZMlZmYm1GdFpUb0tiRzlqWVd3PSIsImV4cCI6IjIwMjQtMDItMTFUMTQ6NTM6NDguOTM4WiIsInB1ciI6ImJsb2Jfa2V5In19--7fcf957d29c377e1d1b42444ad764b04b4c2a5a4/debate_background.jpg" for 127.0.0.1 at 2024-02-11 16:48:49 +0200
Processing by ActiveStorage::DiskController#show as JPEG
  Parameters: {"encoded_key"=>"[FILTERED]", "filename"=>"tim-mossholder-302931-unsplash_713x475"}
Completed 200 OK in 2ms (ActiveRecord: 0.0ms | Allocations: 372)

Started GET "/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBYVU9IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f8b17c77f81850e5ce730e295cafdb707ecad7e3/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2QzNKbGMybDZaVWtpQ1hnME56VUdPd1pVT2dwemRISnBjRlE9IiwiZXhwIjpudWxsLCJwdXIiOiJ2YXJpYXRpb24ifX0=--a96910212db13c6324d1e77d9f4934b201e9deb1/budget_background.jpg" for 127.0.0.1 at 2024-02-11 16:48:49 +0200
Processing by ActiveStorage::DiskController#show as JPEG
  Parameters: {"encoded_key"=>"[FILTERED]", "filename"=>"nathan-dumlao-496190-unsplash_713x475"}
Completed 200 OK in 2ms (ActiveRecord: 0.0ms | Allocations: 326)

Processing by ActiveStorage::DiskController#show as JPEG
  Parameters: {"encoded_key"=>"[FILTERED]", "filename"=>"nathan-dumlao-496190-unsplash_713x475"}
Completed 200 OK in 1ms (ActiveRecord: 0.0ms | Allocations: 320)

Started GET "/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDVG9JYTJWNVNTSWhjalpqY2psMFpEbHdlVFYxYURWd2JISnlOM1kxZW13NE9XWmtOZ1k2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpVldsdWJHbHVaVHNnWm1sc1pXNWhiV1U5SW1obFlXUmxjbDlpWVdOclozSnZkVzVrTG1wd1p5STdJR1pwYkdWdVlXMWxLajFWVkVZdE9DY25hR1ZoWkdWeVgySmhZMnRuY205MWJtUXVhbkJuQmpzR1ZEb1JZMjl1ZEdWdWRGOTBlWEJsU1NJUGFXMWhaMlV2YW5CbFp3WTdCbFE2RVhObGNuWnBZMlZmYm1GdFpUb0tiRzlqWVd3PSIsImV4cCI6IjIwMjQtMDItMTFUMTQ6NTE6MzMuNzE0WiIsInB1ciI6ImJsb2Jfa2V5In19--80bb091da0bcc5061f9b867270231f9b212abb42/header_background.jpg" for 127.0.0.1 at 2024-02-11 16:48:50 +0200
Processing by ActiveStorage::DiskController#show as JPEG
  Parameters: {"encoded_key"=>"[FILTERED]", "filename"=>"proposal_background"}
Completed 200 OK in 5ms (ActiveRecord: 1.3ms | Allocations: 443)

Processing by ActiveStorage::DiskController#show as JPEG
  Parameters: {"encoded_key"=>"[FILTERED]", "filename"=>"debate_background"}
Completed 200 OK in 3ms (ActiveRecord: 0.3ms | Allocations: 469)

Processing by ActiveStorage::Representations::RedirectController#show as JPEG
  Parameters: {"signed_blob_id"=>"eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBYVU9IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f8b17c77f81850e5ce730e295cafdb707ecad7e3", "variation_key"=>"[FILTERED]", "filename"=>"budget_background"}
  ActiveStorage::Blob Load (0.7ms)  SELECT "active_storage_blobs".* FROM "active_storage_blobs" WHERE "active_storage_blobs"."id" = $1 LIMIT $2  [["id", 165], ["LIMIT", 1]]
  ActiveStorage::VariantRecord Load (0.6ms)  SELECT "active_storage_variant_records".* FROM "active_storage_variant_records" WHERE "active_storage_variant_records"."blob_id" = $1 AND "active_storage_variant_records"."variation_digest" = $2 LIMIT $3  [["blob_id", 165], ["variation_digest", "cAksiPRLedvpqAyCfn3vbTzzvrs="], ["LIMIT", 1]]
  ActiveStorage::Attachment Load (0.7ms)  SELECT "active_storage_attachments".* FROM "active_storage_attachments" WHERE "active_storage_attachments"."record_id" = $1 AND "active_storage_attachments"."record_type" = $2 AND "active_storage_attachments"."name" = $3 LIMIT $4  [["record_id", 6], ["record_type", "ActiveStorage::VariantRecord"], ["name", "image"], ["LIMIT", 1]]
  ActiveStorage::Blob Load (0.8ms)  SELECT "active_storage_blobs".* FROM "active_storage_blobs" WHERE "active_storage_blobs"."id" = $1 LIMIT $2  [["id", 171], ["LIMIT", 1]]
  TenantDisk Storage (0.5ms) Generated URL for file at key: zg5ow1waao4p8br6b26zgkuuat3z (http://127.0.0.1:3000/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDVG9JYTJWNVNTSWhlbWMxYjNjeGQyRmhielJ3T0dKeU5tSXlObnBuYTNWMVlYUXplZ1k2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpVldsdWJHbHVaVHNnWm1sc1pXNWhiV1U5SW1KMVpHZGxkRjlpWVdOclozSnZkVzVrTG1wd1p5STdJR1pwYkdWdVlXMWxLajFWVkVZdE9DY25ZblZrWjJWMFgySmhZMnRuY205MWJtUXVhbkJuQmpzR1ZEb1JZMjl1ZEdWdWRGOTBlWEJsU1NJUGFXMWhaMlV2YW5CbFp3WTdCbFE2RVhObGNuWnBZMlZmYm1GdFpUb0tiRzlqWVd3PSIsImV4cCI6IjIwMjQtMDItMTFUMTQ6NTM6NTAuMzgzWiIsInB1ciI6ImJsb2Jfa2V5In19--8bddf3e602c73b60328b599eb58bbd4d458012c1/budget_background.jpg)
Redirected to http://127.0.0.1:3000/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDVG9JYTJWNVNTSWhlbWMxYjNjeGQyRmhielJ3T0dKeU5tSXlObnBuYTNWMVlYUXplZ1k2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpVldsdWJHbHVaVHNnWm1sc1pXNWhiV1U5SW1KMVpHZGxkRjlpWVdOclozSnZkVzVrTG1wd1p5STdJR1pwYkdWdVlXMWxLajFWVkVZdE9DY25ZblZrWjJWMFgySmhZMnRuY205MWJtUXVhbkJuQmpzR1ZEb1JZMjl1ZEdWdWRGOTBlWEJsU1NJUGFXMWhaMlV2YW5CbFp3WTdCbFE2RVhObGNuWnBZMlZmYm1GdFpUb0tiRzlqWVd3PSIsImV4cCI6IjIwMjQtMDItMTFUMTQ6NTM6NTAuMzgzWiIsInB1ciI6ImJsb2Jfa2V5In19--8bddf3e602c73b60328b599eb58bbd4d458012c1/budget_background.jpg
Completed 302 Found in 19ms (ActiveRecord: 2.8ms | Allocations: 8108)

Started GET "/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDVG9JYTJWNVNTSWhlbWMxYjNjeGQyRmhielJ3T0dKeU5tSXlObnBuYTNWMVlYUXplZ1k2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpVldsdWJHbHVaVHNnWm1sc1pXNWhiV1U5SW1KMVpHZGxkRjlpWVdOclozSnZkVzVrTG1wd1p5STdJR1pwYkdWdVlXMWxLajFWVkVZdE9DY25ZblZrWjJWMFgySmhZMnRuY205MWJtUXVhbkJuQmpzR1ZEb1JZMjl1ZEdWdWRGOTBlWEJsU1NJUGFXMWhaMlV2YW5CbFp3WTdCbFE2RVhObGNuWnBZMlZmYm1GdFpUb0tiRzlqWVd3PSIsImV4cCI6IjIwMjQtMDItMTFUMTQ6NTM6NTAuMzgzWiIsInB1ciI6ImJsb2Jfa2V5In19--8bddf3e602c73b60328b599eb58bbd4d458012c1/budget_background.jpg" for 127.0.0.1 at 2024-02-11 16:48:50 +0200
Processing by ActiveStorage::DiskController#show as JPEG
  Parameters: {"encoded_key"=>"[FILTERED]", "filename"=>"header_background"}
Completed 304 Not Modified in 1ms (ActiveRecord: 0.0ms | Allocations: 282)

Processing by ActiveStorage::DiskController#show as JPEG
  Parameters: {"encoded_key"=>"[FILTERED]", "filename"=>"budget_background"}
Completed 200 OK in 1ms (ActiveRecord: 0.0ms | Allocations: 295)`

Also, let's say I log in as user and I navigate to change the header image, when I press the "View image" of the already loaded image, it redirects me, but shots me nothing.

**Comment by javierm** [comment]
Hi, @gzorpidis :smile:. Thank you for reporting this issue.

Just in case, could you include the link to the site where images aren't loading, as well as the link to its source code?

Thanks!

**Comment by javierm** [comment]
Closing due to lack of response. @gzorpidis Feel free to reopen if you can provide links to the site where images aren't loading and its source code.
