### ISSUE TITLE
Admin Statistics not updating due to cache

### ISSUE THREAD

**Issue by coslajohn** [consuldemocracy/consuldemocracy#5393]
### Why this is needed
The admin/statistics page for participatory budgeting is really useful for allowing admins to be able to see how much engagement they are getting during a process.

The way it is behaving at the moment just causes confusion!

### Description

Admin Statistics for Participatory Budgeting appeared to show random values on page 

/admin/stats/budget_balloting?budget_id=

Some of the values on this page never update. Votes per heading appears to be ok, but the other values don't seem to update

After lots of investigation it appears to be a caching issue. 

app/models/budget/stats.rb is caching the stats methods but they do not appear to be ever updated in the cache

Running Rails.cache.clear fixes the issue

For example at 
https://wdn.communitychoices.scot/admin/stats/budget_balloting?budget_id=7

** Before clearing cache
![image](https://github.com/consuldemocracy/consuldemocracy/assets/102246590/b050822d-e9fa-47a6-b125-b9dbc065f400)

and 
https://dundeesvoice.communitychoices.scot/admin/stats/budget_balloting?budget_id=12
![image](https://github.com/consuldemocracy/consuldemocracy/assets/102246590/6de7caa0-adcd-4a6d-933a-6f914532d832)

**after Rails.cache.clear**

![image](https://github.com/consuldemocracy/consuldemocracy/assets/102246590/985ef2d3-b774-4879-a685-ab856805c617)

![image](https://github.com/consuldemocracy/consuldemocracy/assets/102246590/9f3bcd55-82c9-4145-b197-62777cb8945b)

**Comment by javierm** [comment]
It looks like this issue was introduced in commit e51e03446 from pull request #4985.
