### ISSUE TITLE
bug comments are not linked to the original text after edit

### ISSUE THREAD

**Issue by Avi-ADAM** [consuldemocracy/consuldemocracy#5529]
### User Story
when looking at a proposal the comments are linked to the text via yellow marks , but after the text get edited the yellow marks and the comments are in different location from where they originally assigned 

### Why is this Needed?
allow editing proposals while keep the comments linked to text 

*Type*: Bug

### Steps to reproduce
[comment]: # (Describe how we can replicate the bug step by step.)
add comment to proposal then edit the proposal and add some text before the commented text,  you will see that now the comment not linked to the original text

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
comments linked to text not word counter

**Comment by javierm** [comment]
Hi, @Avi-ADAM :smile:.

If we're talking about comments on legislation drafts, this actually works as intended, although I agree that it's confusing.

The idea is that, once a draft version is published and people add comments to it, you no longer edit it (maybe we should add a validation rule for this :thinking:) but create a new draft version instead.

I don't think it's possible to change the current behavior at least until we replace the library we use to add annotations (which is [no longer maintained](https://github.com/consuldemocracy/consuldemocracy/discussions/5495)).
