### ISSUE TITLE
Failure to install due to faker gem not being properly invoked in users.rb

### ISSUE THREAD

**Issue by ediazcomellas** [consuldemocracy/consuldemocracy#5534]
### Why is this Needed?

[comment]: 
Fails to build due to dependency on faker gem, which is not properly imported in users.rb

### Description

[comment]: # (Feature or Bug? eg. Type: Bug)
*Type*: Bug

### Current Behavior
[comment]: 
Breaks while building because it can't fill the users table with fake examples.

**Comment by javierm** [comment]
Hi, @ediazcomellas :smile:. Thanks for reporting!

I cannot reproduce this issue :thinking:. The `faker` gem should be loaded by the `gem "faker"` entry in the Gemfile.

Could you tell us a way to reproduce the error?

**Comment by javierm** [comment]
When you say "try to install", do you mean on your development environment or on a production server? Could you paste the exact command that is giving you the error (as well as the nasty errors you mention)?

**Comment by ediazcomellas** [comment]
Sure. I will make a fresh new install and copy here the output today. 

Thanks a lot for your attention.

**Comment by ediazcomellas** [comment]
Ups... I'm unable to replicate it too. In fact, it was a development environment. I've done a fresh new install and it creates users without a flaw. I'm going to close the issue. Please forgive the noise. 

There are still a lot of packages to install to get it working (besides the ones already stated in the documentation). I will let you know the complete list in case you are interested.

**Comment by javierm** [comment]
> There are still a lot of packages to install to get it working (besides the ones already stated in the documentation). I will let you know the complete list in case you are interested.

A pull request updating the `README.md` file would be welcome!
