### ISSUE TITLE
what is the criteria for archiving a proposal

### ISSUE THREAD

**Issue by YaelShahamGafni** [consuldemocracy/consuldemocracy#5638]
a user published a proposal. there were no supporters.
after some time he noticed that the proposal was archived.

is there any documentation about archiving proposals, what is the criteria for archiving, and what is the time-frame?

**Comment by javierm** [comment]
Hi, @YaelShahamGafni :smile:.

In the [global settings section of the admin area](https://demo.consuldemocracy.org/admin/settings), one of the settings is called "Months to archive Proposals". That number will define when a proposal that doesn't reach the necessary number of supports (which also configured in the admin area) will be archived.

Hope that helps!

**Comment by javierm** [comment]
Hopefully that answers the quesetion. If not, feel free to reopen this issue :wink:.
