### ISSUE TITLE
Translations title for Custom information texts not set

### ISSUE THREAD

**Issue by M3lkior** [consuldemocracy/consuldemocracy#5756]
## User Story

As a user, when i navigate to the Custom information texts
page, with the French locale activated, i wish to see title translated in french.

## Why is this Needed?

the titles don't appears as human readable

## Description

The Custom information texts page is not translated in French

### Current Behavior

![image](https://github.com/user-attachments/assets/78393ba2-94c1-4bb8-9026-7aee6e1b8f43)

### Expected Behavior

All the text must be translated (to french and other langages ?)

### Steps to reproduce

- Run the Consul locally
- Setup the French language
- Login with an admin account
- Go to Site Content -> Custom information texts

### Definition of Done

The titles on the page must be translated

**Comment by EFerrandi** [comment]
Hello, I would like to take this issue. Can I ?

Is there anything I need to know about the translation process or anything else ?

**Comment by M3lkior** [comment]
Sorry, i misunderstand the aim of this page, all in fine

**Comment by javierm** [comment]
Hi, @M3lkior @EFerrandi :smile:.

@M3lkior The interface is certainly confusing; sorry! :pray: As you might have already found out, to display the page in French you need to use the language selector at the top of the screen.

@EFerrandi Thank you very much! We mange translations through [our Crowdin project](https://crowdin.com/project/consul). Currently French is 99% translated, but we certainly welcome more translators to add the missing translations or improve existing ones :smile:.
